tree/config/routes.rb
Tree::Application.routes.draw do
  root :to => 'statuses#index'
  devise_for :users
  resources :statuses

end

tree/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
end

tree/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,presence: true
validates :last_name,presence: true
validates :profile_name,presence: true,
                        uniqueness: true,
                        format:{
                          with: /a-zA-Z0-9_-/,
                          message: 'Must be formatted correctly'
                        }

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name,:last_name,:profile_name,:email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :statuses
  def full_name
    first_name + " " + last_name
  end
end

tree/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

tree/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

tree/app/helpers/application_helper.rb
module ApplicationHelper
end

tree/app/helpers/statuses_helper.rb
module StatusesHelper
end

tree/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Twibook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<a href="/statuses/" class="brand">Twibook</a>
			<ul class="nav">
				<li><%= link_to "All statuses",statuses_path%></li>
			</ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>
				<li><%= link_to current_user.full_name,edit_user_registration_path %></li>
				<li><%= link_to "Sign Out",destroy_user_session_path,method: :delete %></li>
				<% else %>
					<li><%= link_to "Register",new_user_registration_path%></li>
					<li><%= link_to "Login",new_user_session_path%></li>
				<% end %>
			</ul>	
		</div>
	</div>

</div>
</div>
<p class="notice" align="center"><p></p><%= notice %></p>
<p class="alert" align="center"><%= alert %></p>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

tree/app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <legend><%= f.label current_user.full_name%></legend>
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit,class: "btn btn-success"%>
  </div>
<% end %>

tree/app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

tree/app/views/statuses/index.html.erb
<div class="page-header">
	<h1>All statuses</h1>
</div>
<%=link_to "Post a New status",new_status_path,class:"btn btn-success"%>
<% @statuses.each do |status| %>
	<div class="status">
		<strong><%=status.user.full_name%></strong>
		<p><%= status.content %></p>
		<div class="meta">
			<%=link_to time_ago_in_words(status.created_at) + " ago",status %>
	<span class="admin">
			| <%=link_to "Edit",edit_status_path(status)%> |
			<%=link_to "Delete",status,method: :delete,data: {confirm:"Are you sure ?"}%>
		</span>
		</div>
		<p></p>
	</div>
<%end%>

tree/app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path,class: "btn btn-info"%>

tree/app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name%>
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>