chwink/config/routes.rb
ChwinkApp::Application.routes.draw do
  devise_for :users
  
  match '/get_recent_activity', to: 'chwinks#get_recent_activity', via: :get  
  match '/auth/:provider/callback', to: 'authentications#create'
  match '/auth/failure', to: 'authentications#failure'
  match '/chwinks/search', to: 'chwinks#index'
  match '/categories/:category_id', to: 'chwinks#index', as: 'category_chwinks'
  
  resources :chwinks do
    get '/vote/:year', to: 'chwinks#vote'
    post '/comment', to: 'chwinks#comment'
  end

  resources :categories do

  end

  root :to => 'home#index'

end

chwink/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @chwinks = Chwink.all 
  end
end

chwink/app/helpers/home_helper.rb
module HomeHelper
end

chwink/app/views/home/index.html.haml
#page-content{:style => "margin-left: 10px;"}
  .row-fluid
    .span6
      %img{:src => "/assets/products_placeholder.png"}
    .span6
      .chwink-title
        What our Chilren Will Never Know
      .chwink-subtitle
        Wouldn't it be great to have all the things our children would never know under one roof? Chwink is informative, collaborative and fun!!
  .row-fluid
    .span8
      #carousel.well.home-wells.carousel.slide
        .row-fluid.home-product.carousel-inner
          - is_first = true
          - @chwinks.each do |chwink|
            .item{:class => is_first ? 'active' : ''}
              - is_first = false
              .span5
                .polaroid
                  .polaroid-img
                    %img{:src => "#{chwink.image.url(:small)}"}
                  .row-fluid.image-info
                    .span4.date
                      #{chwink.ranking.first}
              .span7
                %h2.product-title
                  #{chwink.name}
                .product-info
                  #{chwink.description}
                  %a.btn.btn-medium.btn-chwink-orange.btn-submit-chwink.pull-down.pull-right{:href => "#{chwink_url(chwink)}" }I would like to vote!
        %a.left-arrow.left{:href => '#carousel', 'data-slide' => 'prev'}
        %a.right-arrow.right{:href => '#carousel', 'data-slide' => 'next' }
    .span4
      .well.home-wells.did-you-know
        .title
          Did You Know?
        .info
          %img.pull-right{:src => "/assets/ham_radio.jpg"}
          %p 
            During World War II, priest Fr. Maximilian Kolbe, SP3RN was arrested by the Germans and they believed his amateur
            %b HAM radio 
            activities were involved in espionage. After some prisoners escaped in 1941, the Germans ordered 10 prisoners be killed in retribution. Fr. Kolbe was martyred when he volunteered to take the place of one of the condemned men.
          %h5 Save these Chwinks for our children