chwink/config/routes.rb
ChwinkApp::Application.routes.draw do
  devise_for :users
  
  match '/get_recent_activity', to: 'chwinks#get_recent_activity', via: :get  
  match '/auth/:provider/callback', to: 'authentications#create'
  match '/auth/failure', to: 'authentications#failure'
  match '/chwinks/search', to: 'chwinks#index'
  match '/categories/:category_id', to: 'chwinks#index', as: 'category_chwinks'
  
  resources :chwinks do
    get '/vote/:year', to: 'chwinks#vote'
    post '/comment', to: 'chwinks#comment'
  end

  resources :categories do

  end

  root :to => 'home#index'

end

chwink/app/models/chwink.rb
require 'eventmachine'
class Chwink
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  include Mongoid::Paperclip

  # history tracking all Chwink documents
  # note: tracking will not work until #track_history is invoked
  include Mongoid::History::Trackable
  track_history on: [:name, :description, :region, :culture, :end_year, :own_it], track_create: true, track_update: true, track_destroy: true  
  
  field :name, type: String
  field :description, type: String
  field :region, type: String
  field :culture, type: String
  field :end_year, type: Integer
  field :own_it, type: Boolean, default: true

  # increment fields
  field :votes, type: Hash # maintains the year-votes

  belongs_to :category
  belongs_to :user
  has_mongoid_attached_file :image, PAPERCLIP_CONFIG
  has_many :comments
  
  slug :name
  validates :name, presence: true
  validates :end_year, presence: true, length: { is: 4 }


  before_create do |record|
    record.votes = { record.end_year.to_s => 1 }
  end

  after_update do |record|
    user = User.where(id: record[:modifier_id]).first
    user_image =  "<img width='16px' height ='16px' class='user_image' src=#{user.try(:image)}" + "/>"
    modifier = user.blank? ? "Someone" : user.nickname
    modifier = user_image + modifier
    data = "<a href=/chwinks/#{record.id}> #{record.name}</a>"
    message = modifier + "updated" + data
    message = "<li class='activity'>" + message + "</li>"
    EM.run {
      client = Faye::Client.new('http://localhost:9292/faye')
      client.publish('/activity/public', {message: message})
    } 
  end 

  STOPWORDS = %w(a able about across after all almost also am among an and any are as at be because been but by can cannot could dear did do does either else ever every for from get got had has have he her hers him his how however i if in into is it its just least let like likely may me might most must my neither no nor not of off often on only or other our own rather said say says she should since so some than that the their them then there these they this tis to too twas us wants was we were what when where which while who whom why will with would yet you your) 

  def similar
    Chwink.similar(self.name)
  end

  def self.similar(name)
    search = name.downcase.split(/\W/) - STOPWORDS

    # THE correct regular expression is always returning false. MongoDB 
    # is screwing around!
    #if (new RegExp("\\b" + value + "\\b").test(chwink.name) ) {
    map = %Q{ function() {    
        score = 0;     
        compare = #{search};
        chwink = this;
        compare.forEach(function(value) {
          if(chwink.name.toLowerCase().search(value) != -1) {
            score += 1;
          }
        });
        if (score > 0) {
          emit(score, { id: this._id.str, count: 1} );
        }   
      }
    }

    reduce = %q{ function( key, values) {
        res = { id: '', count: 0}
        values.forEach(function(value) {
          res.id = res.id + "," + value.id;
          res.count += value.count
        });
        return res;
      }
    }

    mr_collection = "#{SecureRandom.hex(4)}_similar"
    res = Chwink.map_reduce(map, reduce).out(replace: mr_collection)

    if res.empty?
      # Return if nothing found
      Chwink.collection.database[mr_collection].drop
      res # []
    else
      ## Fetch similar chwinks
      result = {}
      res.find().to_a.each { |e| result[e["_id"]] = e["value"] }
      result = result[result.keys.max]["id"].split(",").delete_if { |a| a == "" }
      Chwink.collection.database[mr_collection].drop
      Chwink.where(:id.in => result)
    end
  end


  # self.votes is a Hash of { 2012 => 32, 2001 => 3 }
  #
  # params: 
  # votes: A hash containing :up and optionally :down
  # example:
  # { :up => 2012 }                => agree or new
  # { :up => 2012, :down => 1989 } => change
#
# REMEMEBER: MongoDB saves keys as STRINGS, so even if we are setting the
# key as an integer in Ruby, its getting saved as a string in MongoDB. So
# when its retrieved, be sure to convert the key back to an Integer!
# - Got fucked on this - so wrote it down for posterity and converted the
# the keys to strings!!
#
  def vote(year)
    self.votes = {} unless self.votes  # for old data (TO BE DELETED)

    # Add new vote or increment existing vote
    self.votes[year[:up]] = (self.votes[year[:up]].to_i || 0 ) + 1 if year[:up]

    if year[:down]
      # *ideally* there should never be a case where :down is sent and the key is
      # not presentI
      self.votes[year[:down]] = self.votes[year[:down]].to_i - 1
      # delete this if count is 0 
      self.votes.delete(year[:down]) if self.votes[year[:down]].to_i == 0
    end
    self.save(validate: false) # don't validate for speed
  end

  # Calculates at run-time, the ranking of the year and returns top 5 by default
  def ranking(limit=4)
    return [] unless self.votes ## empty array if no ranks
    self.votes.map.sort {|x, y| y[1] <=> x[1] }.collect {|y| y[0] }[0..limit]
  end


  def get_user_selection(user)
    self.comments.votes.by_user(user).first.year.to_s rescue nil
  end
end

chwink/app/controllers/chwinks_controller.rb
class ChwinksController < ApplicationController
  include ChwinksHelper
  before_filter :login_required, :only => [:vote, :create, :comment]

  def index
    @chwink = Chwink.new
    @slide_index = 0
    @comments = []
    @chwinks = {"timeline" =>{"date" => []}}
    if params[:query].blank? and params[:category_id].blank? and params[:id].blank?
      chwinks = Chwink.all
    elsif !params[:query].blank?
      chwinks = Chwink.similar(params[:query])
    elsif !params[:category_id].blank?
      category = Category.find(params[:category_id])
      chwinks = category.chwinks
    elsif !params[:id].blank?
      first = Chwink.find(params[:id])
      chwinks = Chwink.similar(first.name)
    end
    absolete_text = "obsoleted" 
    chwinks.each do |chwink|
      facebook_url = "#{FACEBOOK_SHARE_URL}#{HOST_URL}chwinks/#{chwink.slug}"
      absolete_text = Date.today.year < chwink.end_year ? "was obsoleted since #{chwink.end_year}" : "will be obsolete from #{chwink.end_year}"
      twitter_url = "#{TWITTER_SHARE_URL}#{chwink.name} #{absolete_text}  #{HOST_URL}chwinks/#{chwink.slug}"
      hash ={"startDate" => chwink.ranking.first.to_s, 
            "endDate" => chwink.ranking.first.to_s, 
            "headline" => chwink.name, 
            "text" => chwink.description, 
            "slug" => chwink.slug, 
            "asset" => {
              "media" => chwink.image.url(:small), 
              "thumbnail" => chwink.image.url(:thumb), 
              "caption" => chwink.category.name, 
              "credit" => chwink.user.try(:name), 
              "type" => "image", 
              "user_image" => chwink.user.try(:image), 
              "facebook_link" => facebook_url, 
              "twitter_link" => twitter_url
            },
            "votes" => {
              "ranking" => chwink.ranking,
              # give it a shot - if users selection is ranked, show it ;)
              "selected" => chwink.get_user_selection(current_user)
            }
      } 
      @chwinks["timeline"]["date"] << hash
      @comments << chwink.comments
    end
    first = chwinks.first if first.blank?
    facebook_url = "#{FACEBOOK_SHARE_URL}#{HOST_URL}chwinks/#{first.slug}"
    twitter_url = "#{TWITTER_SHARE_URL}#{first.name}#{HOST_URL}chwinks/#{first.slug}"
    #@chwinks["timeline"]["headline"] = first.name
    @chwinks["timeline"]["type"] = "default"
    #@chwinks["timeline"]["text"] = first.description
    @chwinks["timeline"]["startDate"] = first.ranking.first.to_s
    @chwinks["timeline"]["slug"] = first.slug
    @chwinks["timeline"]["votes"] = { "ranking" => first.ranking } 
    @chwinks["timeline"]["asset"] = {"media" => first.image.url(:small), 
                              "thumbnail" => first.image.url(:thumb), 
                              "caption" => first.category.name, 
                              "credit" => first.user.try(:name), 
                              "type" => "image", 
                              "user_image" => first.user.try(:image), 
                              "facebook_link" => facebook_url, 
                              "twitter_link" => twitter_url}
    @comments = @comments.flatten
    @chwinks = @chwinks.to_json
  end

  def show
    redirect_to chwinks_path(:id => params[:id])
  end


  def create
    @chwink = Chwink.new(params[:chwink])
    @chwink.user = current_user
    @chwink.save
    if @chwink.errors.any?
      flash[:notice] = "Chwink added successfully"
    else
      flash[:errors] = "some error occured while adding chwink"
    end
    session[:action] = "create"
    session[:user_id] = current_user.id
    session[:chwink_id] = @chwink._id
    redirect_to chwinks_url(:id => @chwink.slug)
  end

  def get_recent_activity
    @latest_activity = {recent_activity: {data: []}}
    ActivityTracker.all.order_by(created_at: :desc).limit(5).each do|actv|
      hsh = {message: build_activity_logs(actv) }
      @latest_activity[:recent_activity][:data] << hsh      
    end unless ActivityTracker.where('association_chain.name' =>  "Chwink").first.blank?
    @recent_activity = @latest_activity.to_json
    
    render json: @recent_activity 
  end

  def comment
    comment = Comment.new(params[:comment])
    chwink = Chwink.find(params[:chwink_id])
    comment.chwink = chwink
    comment.user = current_user
    comment.save

    render :json => {:nickname => current_user.nickname, :chwink_id => chwink.slug, :chwink_name => chwink.name, :profile_image => current_user.image}
  end

  def vote
    # Check if user has already voted for this chwink.
    chwink = Chwink.find(params[:chwink_id])

    if chwink.comments and (@vote = chwink.comments.votes.by_user(current_user).first)
      chwink.vote(:up => params[:year], :down => @vote.year.to_s)
      @vote.year = params[:year]
      @vote.save
    else
      @vote = chwink.comments.create(user: current_user, type: Comment::VOTE, year: params[:year].to_i)
      chwink.vote(:up => params[:year])
    end
  end
end

chwink/app/helpers/chwinks_helper.rb
module ChwinksHelper
  def build_activity_logs(actv)
    message = nil 
    action = nil
    modifier = nil
    data = nil
    user = User.where(id: actv[:modifier_id]).first
    user_image =  "<img width='16px' height ='16px' class='user_image' src=#{user.try(:image)}" + " />"
    modifier = actv[:modifier_id].blank? ? "Someone" : user.nickname
    modifier = user_image + modifier
    if actv.association_chain[0]["name"] == "Comment"
      comment = Comment.where(id: actv.association_chain[0]["id"]).first
      chwink = comment.try(:chwink)
      if actv[:action] == "create"
        action = " commented on chiwnk "
      end
      data = "<a href=#{chwink_path(id: chwink.try(:id))}> #{chwink.try(:name)}</a>"
    else
      chwink = Chwink.where(id:  actv.association_chain[0]["id"]).first  
      data = "<a href=#{chwink_path(id: chwink.id)}> #{chwink.name}</a>"
      if actv[:action] == "create"
        action = " added a chwink called "
      elsif actv[:action] == "update"
        modifier = actv[:modifier_id].blank? ? "Someone" : user.nickname
        action = " has updated information"
      end
    end
 
    message = modifier + action + data  
    message.html_safe  
  end
end

chwink/app/views/chwinks/_activity.html.haml
#activitywindow
  #messagewindow
    %ul

chwink/app/views/chwinks/_add_chwink.html.haml
.well.home-wells
  .well-head
    Chwink Details
  = simple_form_for @chwink,  html: {multipart:true} do |f|
    .row-fluid
      .span4 Name *
      .span
        = f.input :name, label: false, input_html: {class: 'input-medium', placeholder: 'Chwink Name'}
    .row-fluid
      .span4 Image 
      .span2 
        = f.file_field :image, label: false, class: "input-medium"
    .row-fluid
      .span4 End Year *
      .span1
        = f.input :end_year, label: false, input_html: {class: 'input medium', placeholder: '1998', style: "width:150px;"}
    .row-fluid
      .span4 Category *
      .span
        .control-group
          .controls
            = f.association :category, label: false, collection: Category.all, prompt: "Choose the category", required: true, input_html:{ class: "input-medium"} 
    .row-fluid
      .span4
        Description
      .span
        .control-group
          %label.control-label{:for => "textarea"}
          .controls
            //%textarea#textarea.input-medium{:rows => "4"}
            = f.input :description, label: false, :as => :text, input_html: { class: 'input-medium', rows: '4' } 
    .row-fluid        
      %strong Edits are obsolete ;) Create with care!
      = f.submit 'Chwink It!', class: 'btn btn-medium btn-chwink-orange btn-submit-chwink'
        
        


  

chwink/app/views/chwinks/_categories.html.haml
.row-fluid.nav-category
  - @categories.each do |category|
    .span6
      %a{:href => "#{category_chwinks_url(category)}"}= category.name

chwink/app/views/chwinks/_comments.html.haml
#chwink_comment.modal.hide.fade
  .modal-header
    %button.close{:type => 'button', :data => {:dismiss => "modal"}, :aria => {:hidden => "true"}}
    %h3 Add a comment
  .modal-body
    = form_for(Comment.new, :url =>'#', :remote => true) do |f|
      = f.text_area :comment, :rows => '5', :columns => '40', style: "width: 350px;"
  .modal-footer
    %button.btn.btn-primary.marginRight10{:type => "submit", :id => "add_comment"} &nbsp; Save &nbsp;
    %button.btn{:type => "submit","data-dismiss" => "modal"} Cancel

chwink/app/views/chwinks/_list_comments.html.haml
#commentlist
  #commentwindow
    %ul
    - @comments.each do |comment|
      %li.activity
        %a{:href => "#{chwink_path(comment.chwink)}"} 
          = comment.chwink.name
        \:
        %img{ :src => "#{comment.user.image}", :height => "16px", :width => "16px"}
        = comment.user.name
        says, '
        = comment.comment
        \'  

chwink/app/views/chwinks/index.html.haml
%script
  $(document).ready(function() {
  createStoryJS({
  type:       'timeline',
  width:      '640',
  height:     '600',
  source:     #{raw @chwinks},
  embed_id:   'my-timeline',
  debug:      false,
  start_at_slide: #{@slide_index},
  });
  });
#page-content
  .row-fluid
    .span8.showmered
      #my-timeline     
    .span4
      .accordion#add_chwink_activity
        .accordion-group
          .accordion-heading
            = link_to "<i class='icon-arrow-up'></i> Add a Chwink".html_safe, "#add_chwink_section", data: {parent: "#add_chwink_activity", toggle: "collapse"}, class: 'accordion-toggle'
          .add-column.accordion-body.collapse#add_chwink_section
            = render 'add_chwink'
        .accordion-group
          .accordion-heading
            = link_to "<i class='icon-arrow-down'> </i> Activity".html_safe, "#activity_section", data: {parent: "#add_chwink_activity", toggle: "collapse"}, class: 'accordion-toggle'
          .add-column.accordion-body.collapse#activity_section  
            = render "activity"
        .accordion-group
          .accordion-heading
            = link_to "<i class='icon-arrow-down'></i> Comments".html_safe, "#comments_section", data: {parent: "#add_chwink_activity", toggle: "collapse"}, class: 'accordion-toggle'
          .add-column.accordion-body.collapse#comments_section
            = render "list_comments"

= render 'comments'
:javascript
  

  $(document).ready(function(){
    
    function broadcast_msg(broadcast_json)
    {
      var msg = "Default Message ";
      switch (broadcast_json.action)
      {
        case 'create':
          msg = "<li class=activity>" + broadcast_json.user+  " added a chwink called " + "<a href='#'>"+ broadcast_json.chwink +"</a> </li>";
          break;
        case 'update':
          msg = "<li class=activity>" + broadcast_json.user+  " updated information about " + "<a href='#'>"+ broadcast_json.chwink +"</a> </li>";
          break; 
      }
      return msg;
      
    }
    
    var need_broadcast = "#{@to_be_broadcast}"
    if(need_broadcast == "true")
    {
      broadcast_data = '#{@broadcast_data}'
      msg = broadcast_msg(JSON.parse(broadcast_data)); 
      console.log("broadcasting"); 
      client.publish('/activity/public', {'message': msg});
    }
    
    $('.accordion').on('show hide', function(e){
      $(e.target).siblings('.accordion-heading').find('.accordion-toggle i').toggleClass('icon-arrow-down icon-arrow-up', 200);
    });


    var activity_subscription = client.subscribe('/activity/public', function(data){
      $('#messagewindow ul').prepend(data.message);                             
    }); 
  });
      

chwink/app/views/chwinks/vote.js.haml
:plain
  $("##{@vote.chwink.slug} .check").css("background-position", "-20px 0")
  $("##{@vote.chwink.slug} .check[data-year=#{@vote.year}]").css("background-position", "0 0")