census/config/routes.rb
Census::Application.routes.draw do
  devise_for :users
  resources :surveys
  resources :home
  root :to => "home#index"

end

census/app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :user_id, :option_id, :question_id, :survey_id
  belongs_to :user
  belongs_to :question
end

census/app/models/option.rb
class Option < ActiveRecord::Base
   attr_accessible :desc, :question_id
   belongs_to :question
   validates :desc, uniqueness: {scope: :question_id},presence: :true
end

census/app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :desc, :survey_id, :options_attributes
  belongs_to :survey
  has_many :options, dependent: :destroy
  has_many :answer
  validates :desc, uniqueness: {scope: :survey_id},presence: :true, length: {minimum: 10}
  validates :options, length: {minimum: 4,message: 'must have 4 options'}
  accepts_nested_attributes_for :options, allow_destroy: :true
end

census/app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :year, :questions_attributes
  has_many :questions, dependent: :destroy
  has_many :options ,through: :questions
  has_many :answers ,through: :questions
	validates :name, presence: :true,uniqueness: :true, length: {minimum: 4, message: 'must be 4 characters long'}
  validates :year, numericality: :true
  validates :questions, length: {minimum: 3, message: 'must have atleast 3 questions'}
  accepts_nested_attributes_for :questions, allow_destroy: :true
end

census/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :answers_attributes
  # attr_accessible :title, :body
  has_many :answers
  accepts_nested_attributes_for :answers
  validates :name, presence: :true,
                           length: {minimum: 6},
                           format: {with: /\A[a-zA-Z]+\z/},
                           uniqueness: :true
end

census/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

census/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    redirect_to surveys_path
  end

  def show
    redirect_to surveys_path if User.find(current_user.id).answers.where(survey_id: params[:id]).first.nil? == false
    @survey = Survey.find(params[:id])
    @user = User.find(current_user.id)
 		@questions = @survey.questions.includes(:options).each
  end

  def update
    @user = User.find(params[:id])
    params[:select].each do |ques|
      option=Option.find(ques[1])
      Answer.create(option_id: option.id, question_id: option.question_id, user_id: @user.id, survey_id: option.question.survey_id)
    end
    redirect_to surveys_path
  end

end

census/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys=Survey.all
  end

  def new
    redirect_to action: 'index' if current_user.name != 'pkrawat'
    @survey=Survey.new
    3.times do
      @survey.questions.build
      4.times do
        @survey.questions.last.options.build
      end
    end
  end

  def create
    redirect_to action: 'index' if current_user.name != 'pkrawat'
    @survey=Survey.new(params[:survey])
    #flag=true
    #print params
    #if @survey.questions.length > 2 and @survey.questions.each{|q| flag=false if q.options.length != 3}
      if @survey.save!# and flag
        redirect_to surveys_path
      else
        render action: 'new'
      end
    #else
     # render action: 'new'
   # end
  end

  def edit
    redirect_to action: 'index' if current_user.name != 'pkrawat'
    @survey = Survey.find(params[:id])
  end
  
  def update
    redirect_to action: 'index' if current_user.name != 'pkrawat'
    @survey=Survey.find(params[:id])
    if @survey.update_attributes(params[:survey])
      redirect_to surveys_path
    else
      render action: 'edit'
    end
  end
  
  def destroy
    render action: 'index' if current_user.name != 'pkrawat'
    Survey.destroy(params[:id])
    render action: 'index'
  end
  
  def show
    @survey = Survey.find(params[:id])
    @questions = @survey.questions.includes(:options,:answer)
  end

end

census/app/helpers/application_helper.rb
module ApplicationHelper
end

census/app/helpers/home_helper.rb
module HomeHelper
end

census/app/helpers/surveys_helper.rb
module SurveysHelper
end

census/app/views/home/show.html.haml
%h1.some{style: "color: green"} Take Survey
%h2 
  Survey : 
  = @survey.name
  %br
  Year:
  =@survey.year
= nested_form_for @user, url: home_path(@user)  do |f|
  - @questions.each do |ques|
    %ul
      %li
        Q.
        = ques.desc
        %ul
          - ques.options.each do |op|
            %li
              = radio_button('select',ques.desc,op.id)
              =op.desc
  = f.submit 'Submit',class: "btn btn-warning"

census/app/views/layouts/application.html.haml
%html
  %head
    %title Census 
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  %div.navbar.navbar-fixed-top.navbar-inverse
    %div.navbar-inner
      %div.container
        %a.brand{:href => "/home"} Census
        %ul.nav
          %li
            = link_to "Home",surveys_path
        %ul.nav.pull-right
          - if user_signed_in?
            %li
              = link_to current_user.name,edit_user_registration_path
            %li
              = link_to "Sign Out",destroy_user_session_path,method: :delete
          - else
            %li
              = link_to "Register",new_user_registration_path
            %li
              = link_to "Login",new_user_session_path
  %div.some{style: "padding-top : 2%", align: "center"}
    %p.alert
      = alert
    %p.notice 
      = notice
%div.container=yield

census/app/views/surveys/_form.html.haml
%div.well
  = nested_form_for @survey do |f|
    - if @survey.errors.any?
      %ul.alert
        %h4
          = @survey.errors.size
          Errors Occured
        = @survey.errors.full_messages.each do |error|
          %li= error
    %br
    = f.label 'Name'
    = f.text_field :name
    = f.label 'Year'
    = f.select(:year,options_for_select(Time.now.year..2015))
    %ol
      = f.fields_for :questions do |q|
        %br
        %li
          = q.text_field :desc, placeholder: 'Question'
          = q.link_to_remove 'Remove question'
          %ol
            = q.fields_for :options do |op|
              %li  
                = op.text_field :desc, placeholder: 'Option'
                = op.link_to_remove 'Remove option'
          =q.link_to_add 'Add option', :options
    =f.link_to_add 'Add Question', :questions
    %br= f.submit 'Save',class: "btn btn-info"

census/app/views/surveys/edit.html.haml
%h1 Edit Survey
%br
= render 'form'

census/app/views/surveys/index.html.haml
%h1.page-header.some{style: "padding-top: 2%"} All Surveys
%table.some{width: "50%"}
  %thead.some{style: "color: green"}
    %th Name
    %th Year
    %th Action
  - @surveys.each do |survey|
    %tr.some{align: "center"}
      %td 
        = survey.name
      %td 
        = survey.year
      %td
        -if current_user.name == 'pkrawat'
          = link_to 'Edit',edit_survey_path(survey)
          = link_to 'Delete',survey_path(survey), method: :delete, confirm: 'Are you sure ?'
        = link_to 'Show' ,survey
      %td= link_to 'Take Survey',home_path(survey),class: "btn" if User.find(current_user.id).answers.where(survey_id: survey.id).first.nil?
%br    
= link_to 'Create Survey',new_survey_path,class: "btn btn-warning" if current_user.name == 'pkrawat'

census/app/views/surveys/new.html.haml
%h1 New Survey
%h1
= render 'form'

census/app/views/surveys/show.html.haml
%h1.some{style: "color: green"} Show Survey
%h2 
  Survey Name : 
  = @survey.name
  %br 
  Year : 
  = @survey.year
-@questions.each do |ques|
  %ul
    %li
      = ques.desc
      %ul
        -ques.options.each do |op|
          - if ques.answer[0].nil? == true
            %li=op.desc
          - else
            - if current_user.id == ques.answer[0].user_id and ques.answer[0].option_id == op.id
              %li.some{style:"color: red"}=op.desc
            - else
              %li=op.desc